### ISSUE TITLE
[Crash Report]: Failure to read WMA file, followed by crash due to SecurityException

### ISSUE THREAD

**Issue by Fendse** [chr56/Phonograph_Plus#112]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.0.1 (1001)
Git Commit Hash: 543ee277190bd8c0fb89
Android version: 9 (SDK 28)
Device brand:    HUAWEI  (by HUAWEI)
Device model:    LON-L29 (code: HWLON)
Product name:    LON-L29
Build version:   LON-L29 9.1.0.254(C432E7R1P6) 
                 (254C432)
Hardware:        hi3660
Language:        sv

java.lang.SecurityException
	at android.media.MediaPlayer.setPlaybackParams(Native Method)
	at ib.c.a(Unknown Source:45)
	at ib.c.start(Unknown Source:4)
	at ib.n.g(SourceFile:79)
	at ib.n.access$playImp(Unknown Source:0)
	at ib.k.invoke(SourceFile:20)
	at ib.g.handleMessage(Unknown Source:237)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Steps to reproduce the bug

1. Attempt to play a `.wma` file

### Other helpful information

Along with the crash, I get the following internal error:

```
Internal Error:

Package name:    player.phonograph.plus
App version:     1.0.1 (1001)
Git Commit Hash: 543ee277190bd8c0fb89
Android version: 9 (SDK 28)
Device brand:    HUAWEI  (by HUAWEI)
Device model:    LON-L29 (code: HWLON)
Product name:    LON-L29
Build version:   LON-L29 9.1.0.254(C432E7R1P6) 
                 (254C432)
Hardware:        hi3660
Language:        sv

Failed to read song file

z8.a: For file /storage/emulated/0/Music/Soundtracks Etc/Syara - DJ Plaeskool.wma the File Header missing. Invalid ASF/WMA file.
	at u8.a.c(Unknown Source:61)
	at r8.b.a(SourceFile:97)
	at ua.f.access$parseEmbedded-u6xRVf4(SourceFile:6)
	at ua.c.invokeSuspend(Unknown Source:12)
	at o6.a.resumeWith(Unknown Source:8)
	at e7.l0.run(Unknown Source:106)
	at kotlinx.coroutines.internal.g.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:65)
}
```

This happens for every `.wma` file I have tried, and for no non-`.wma` files I have tried. I am not familiar enough with the format to determine if the files I'm trying to play are *actually* malformed, but I *am* able to play these files on desktop, as well as in the music player that came pre-installed on my phone with no issue.

### Version

1.0.1 (1001)

**Comment by chr56** [comment]
Turn off Lyrics function, and try again.

**Comment by chr56** [comment]
Well, `Windows Media Audio (WMA)` is not supported by Android OS. And Phonograph Plus is currently relaying on OS to decode media.

So, **I have to no way to fix this**.

Now, there is two ways to solve this:

1) Convert your audio files to other format. (**Suggested**)
`WMA` is Microsoft's format/codecs, is proprietary and non-free. Due to licence conflicting or concerning of patents, many open source software (like AOSP) won't support it. So, try to convert these audio to other open and free formats, which are "more compatible" for most platforms.


2) Wait for me to implement integrating a 3rd-party decoder to Phonograph Plus.
But this is temporarily planning on late 2024 or early 2025.


Reference: 
- [Android Supported media formats](https://developer.android.com/guide/topics/media/platform/supported-formats?hl=en)
- [Windows Media Audio](https://en.wikipedia.org/wiki/Windows_Media_Audio)
- [Advanced Systems Format](https://en.wikipedia.org/wiki/.wma).

**Comment by Fendse** [comment]
I understand that, but the fact that the entire app crashes upon encountering an unsupported file *does* still leave the app largely unusable until I convert/remove *every* such file

When I try placing, say, a `.txt` file in a music directory, the app doesn't display it at all – I feel like that might be a nicer way to handle unsupported audio formats than crashing. Just silently skipping the file would also be an improvement, since that would still mean the app isn't subject to random (in the literal sense) crashes when left on shuffle
