### ISSUE TITLE
[Bug]: Can't input kanji in search bar when using Gboard Japanese input method 

### ISSUE THREAD

**Issue by hingbong** [chr56/Phonograph_Plus#122]
### Bug Summary

When using Gboard Japanese input method to input in search bar, it can't select options in the candidates 

### Version

1.2.0

### Screenshots or Screen recordings

https://github.com/chr56/Phonograph_Plus/assets/26398240/f6e46584-e5a4-4589-8e55-d5b963e04d14

### Environment

Moto edge 30 ultra with Android 13

**Comment by chr56** [comment]
Confirmed.

This caused by confliction between IME's **Inline Composition** and real time search: 
As you can see, IME's Candidate Bar is blinking once and then disappears due to Search Result's update. (So you can not input anything except hiragana which can be input without Candidate Bar.)

Actually, for Gboard, Chinese IME _with Inline Composition enabled_ has the same problem as well. (But Inline Composition is disabled by default, so currently I have not received any similar report from Chinese User. ~And I haven't been using Gboard after switching to fcitx-for-android, plus my music library is "Latin script based", hence I can not notice this.~ However, for Japanese IME it is enabled by default and has no option to turn off.)

For now, the only solution to this I can come up with is disabling real time search, as allowing ONLY _executing searching after committing by Enter_.



Now here is a Sample Preview Release:
[Preview.zip](https://github.com/chr56/Phonograph_Plus/files/12707777/Preview.zip)

which adds _an option to turn off real time search_,

, if you do not mind using Preview. (Or just input non-kana texts in other textbox and copy to it as a workaround.)

**Comment by chr56** [comment]
[v1.3.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.3.0) has released! Close!
