### ISSUE TITLE
[Feature Request] Startup Folder preference in Files  Page or Folders Page

### ISSUE THREAD

**Issue by EkkiBrue** [chr56/Phonograph_Plus#126]
I really love Phonopraph. Thank you all for your time, effort and  passion you put in it. but I´d like to request a small feature to make Phonograph the 110% perfect player for me.

I use a folder based approach using my local MP3 collection on my SD Card. Everytime I start the app in folder mode I have to select my main folder on the sdcard because it defaults back to the Android Folder and does not recognize my last used folder. So my feature-request is a preferences setting where I can define a

"startup folder"

 or 

"LAST Folder used"

It would be a blast if this preferenced for folder mode could be implemented.
Thank you very very much...

**Comment by chr56** [comment]
Are you using `Folders` Page? This feature would not be implemented since `Folders` is for displaying flatten folders by design. 
If you are using `Files` Page, the feature is already there. Just set your folder as start directory in menu. (unless you want to set your root folder as start directory.)

**Comment by EkkiBrue** [comment]
oh. wow... Yes I´m using "files" and I just checked - and yes - it´s there. I didn´t find it because it´s not it the preferences but in the sub sub menu ;) Thanx alot for your support!

**Comment by chr56** [comment]
If you do not have more questions, this issue shall be closed soon.
