### ISSUE TITLE
[Bug Report] Player doesn't show lyrics anymore.

### ISSUE THREAD

**Issue by maemunman** [chr56/Phonograph_Plus#13]
**Describe the bug or unexpected behavior**
The player used to show an icon in the upper corner if the track had lyric metadata, but it doesn't anymore. Sometimes, I can look at the lyrics if I open the tag editor, but the tag editor can't work with some of the containers/codecs I have in my library.

**How to reproduce**
Play a song that has lyric metadata. Find no lyrics icon.

**Screenshots (Optional)**
For example:
![Screenshot_۲۰۲۲۰۷۰۵-۲۳۱۴۴۰_Phonograph Plus](https://user-images.githubusercontent.com/32847759/177481634-860222e4-ded4-4ffc-8629-aeae43e72a88.jpg)
![Screenshot_۲۰۲۲۰۷۰۵-۲۳۱۴۴۹_Phonograph Plus](https://user-images.githubusercontent.com/32847759/177481637-bb7f17c1-f9a1-4b29-8616-44547e70a810.jpg)

there should be a lyrics button next to the heart button, but in the last couple versions it doesn't appear

**Comment by chr56** [comment]
Is it Preview Version? Can you tell me which version started to show no lyrics button like this?

**Comment by chr56** [comment]
However, I can still not locate where the problem is. And "it still works fine for me on my all devices".

And, "lyrics icon button is not shown" could be the problem that player can not find lyrics.

Lyrics have three source:
1) song tags (embed lyrics)
2) lyrics file (`txt ` or `lrc`) with the same file name in same directory (external lyrics)
3) lyrics files (`txt ` or `lrc`) which their name contains file names or song names in same directory (external lyrics)
Please check your song files and lyrics files

**Comment by maemunman** [comment]
It actually seems to be working again, except for OPUS files (which already hadn't been working, so I think it's safe to close this issue)
