### ISSUE TITLE
[Bug]: System button bar have white buttons over white background in player's view on older Android

### ISSUE THREAD

**Issue by Porkepix** [chr56/Phonograph_Plus#131]
### Bug Summary

At least in player's view (didn't see in others, by I didn't try all the views), system buttons bar have white buttons over white background on older Android versions.

See this screenshot:
<details>
<summary>
Screenshot
</summary>

![Screenshot_20231029-135152](https://github.com/chr56/Phonograph_Plus/assets/709500/de2f7c71-e1cb-4f98-9b08-f4acfceaf69b)
</details>

And for reference those similar issues:
https://github.com/Livinglist/Hacki/issues/184
https://github.com/beemdevelopment/Aegis/issues/531
https://github.com/celzero/rethink-app/issues/802

### Version

1.3.2

### Environment

Android Oreo (8.0), stock ROM

**Comment by chr56** [comment]
Well, actually we can **not** resolve this.

As we known:
1. Normally, Phonograph (Plus) use dark Navigation Bar / System Bar as usual, and these buttons use white color.
2. In some place (Main Player), the color of Navigation Bar / System Bar will **dynamically** change based on images palette/prominent color.

However, **only after Android O (8.0)**, there are APIs provided by Android to change the color of Navigation Bar Buttons / System Bar Buttons color _dynamically_ or _programmatically_. Before that, we can not change color these buttons except hard-coding to _theme_ resource.

Since the color of Navigation Bar / System Bar may be dark or light _dynamically_ or _randomly_, and no way to change buttons or icons on it _dynamically_ or _programmatically_ before Android O, and we could not hard code these colors, _nothing can be done so far_.

**Comment by chr56** [comment]
Since [v1.9.0-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.9.0-dev1), mechanism of coloring navigation bar has been updated. 
(This may fixed your issues or may not, it's untested on Android 8)

This issue is outdated.
