### ISSUE TITLE
Excluded media files show up in music list

### ISSUE THREAD

**Issue by stuffi3000** [chr56/Phonograph_Plus#138]
### Bug Summary

Hello,
The Phonograph music list shows me media files that I have excluded from the Media Store, either by ways of a .nomedia file or by specifically adding a certain folder to the exclusion list in Phonograph.
I have added several screenshots to explain the above. As you can see, all those PTT files from WhatsApp still appear in my list.

What should I do? 

Best regards,
Stuffi

### Version

1.4.2

### Steps to reproduce the bug

Happened when I switched to a new phone.

### Environment

Samsung Galaxy S23
Android 14
Stock ROM
OneUI 6.0

### Screenshots or Screen recordings

![Screenshot_20231209_135437_Phonograph Plus](https://github.com/chr56/Phonograph_Plus/assets/11315157/d81be6c0-1316-4302-80ee-986d5c7e2fb2)
![Screenshot_20231209_135355_Material Files](https://github.com/chr56/Phonograph_Plus/assets/11315157/c76c9ff4-abe3-4747-919f-d7bda89ed726)
![Screenshot_20231209_135414_Phonograph Plus](https://github.com/chr56/Phonograph_Plus/assets/11315157/84abfd1e-47e2-4454-9811-c3c80ed6f794)
![Screenshot_20231209_135423_Phonograph Plus](https://github.com/chr56/Phonograph_Plus/assets/11315157/729113b0-5c8f-470c-a748-7c954bd5c4be)

**Comment by chr56** [comment]
I am not sure what the actual problem is.

Try to:

1) use shorter path, like `/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/`;
2) rescan the `MediaStore`: `Drawer Menu` -> `Scan media`;
3) reboot your phone. (Since `.nomedia` file has already created, your device's `MediaStore `should 
 hide them from apllications but it has not, maybe a reboot may help you refresh your device's `MediaStore `_mandatorily_).

**Comment by stuffi3000** [comment]
Shorter path in the blacklist worked.

Thank you!

**Comment by chr56** [comment]
Close issue yourself if you has no more problem or question.
