### ISSUE TITLE
[Bug Report] progress bar in notification stuck on maximum

### ISSUE THREAD

**Issue by Morphior** [chr56/Phonograph_Plus#15]
**Describe the bug or unexpected behavior**
Whenever I play an album or playlist (more than one song), on every song after the first one the progress bar is stuck on the maximum. Example: if the song is 4:02 long, it's stuck on 4:02 out of 4:02 and doesn't move. 

**How to reproduce**
For me it's just to play any album or playlist with more than one song. I also only have FLAC files in the app so maybe that's it but I can't test that right now.

**Comment by chr56** [comment]
I am not sure, either. It happened to me as well. And you can pause once and then play to temperately fix this.
It could be a bug that the Notification haven't been refreshed something (Yeah, sometimes you can also see the image or even song title with artist stuck at previous songs.)

**Comment by chr56** [comment]
_If you are still using Phonograph Plus, please read:_

`MusicService` (with Media Notification) has been refactored since [v0.3.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.0-rc1) (_2022.8.8_).
And I have not seen this bug since then.

I think it was fixed at that time. Also, it is also possible that this bug might be a bug of Android (I can see other software meeting this bug). So, maybe, this bug of system might be fixed in a monthly Android Update.

**Comment by chr56** [comment]
Close for no responding.
