### ISSUE TITLE
[Bug] Duplicated Folder tabs?

### ISSUE THREAD

**Issue by lekanteto** [chr56/Phonograph_Plus#150]
I cannot figure out why "folders" shows up twice in the tab bar. What is the difference between these 2 tabs?

**Comment by chr56** [comment]
Maybe a bug.

**Comment by lekanteto** [comment]
"FOLDERS" also shows up twice in the side drawer as seen in a screenshot in the gallery:

https://github.com/chr56/Phonograph_Plus/blob/dev/docs/Gallery.md

**Comment by chr56** [comment]
This is Bug.

_Folder_ tab was introduced in v0.6.0.
In the process of Version Migration, _Folder_ tab would be amended if user upgrade from versions _before_ v0.6.0. 

However, there is a bug that a _"new installation"_ (user first install it) would be considered as a version before v0.6.0 by mistake. So anyone who first installs Phonograph Plus after v0.6.0 (about 2023 March) would have an extra _Folder_ tab at end, due to Version Migration at the initialization. 

This bug has been fixed in Commit 9cdeef54282.
(Version Migration would not be run for new users).

**Comment by chr56** [comment]
Phonograph Plus [v1.5.0](https://github.com/chr56/Phonograph_Plus/releases/tag/c) has been released. 

New users would not meet the problem again.
And existed users shall** unchecked one of tabs manually** in Settings.

Close!
