### ISSUE TITLE
[Bug] Tags on Ogg/Opus Files are not read and displayed properly

### ISSUE THREAD

**Issue by pixel2user** [chr56/Phonograph_Plus#152]
### Bug Summary

Vinyl had the same problem and fixed it this way:
https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/896#issuecomment-1874464843

### Version

1.4.2

**Comment by chr56** [comment]
Issue of encoding info displaying for opus format has been fixed by applying patch from [drizztbsd/jaudiotagger@164d15ad](https://bitbucket.org/drizztbsd/jaudiotagger/commits/164d15adc272241ee52b68bc3c1c4aada8708103)
[PhonographPlus_1.4.5-dev1-3754d14d.zip] in our [chr56/jaudiotagger@35bc486792](https://github.com/chr56/jaudiotagger/commit/35bc486792e62f9fa708aeecf81f57d14165f279).



Preview Revision: [PhonographPlusPleview-3754d14d](https://github.com/chr56/Phonograph_Plus/files/14217717/PhonographPlus_1.4.5-dev1-3754d14d.zip).

**Comment by pixel2user** [comment]
The sampling rate and bit rate are now correct for the opus file I created with NewPipe.

**Comment by chr56** [comment]
I am not quite sure how it crashed and it is unproducible as well. I guess it is very rare and it happened on the exact instant moment that loading is not completed but you clicked it.

By the way, this fix has been contained in Preview [v1.5-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.5-dev1).

**Comment by chr56** [comment]
Phonograph Plus [v1.5.0](https://github.com/chr56/Phonograph_Plus/releases/tag/c) has been released. Close!
