### ISSUE TITLE
[Bug] Selecting a track with tracks in queue does not work correctly & random playing 

### ISSUE THREAD

**Issue by JukeboxZulu** [chr56/Phonograph_Plus#18]
Prior to the update that added the "Don't clear my queue" option selecting a track would play it immediately and queue whatever was after it based on the context (album, artist, all songs, etc.).

Now, if you already have something playing and tracks in the queue, selecting a track will often play the track after the one you actually tapped on, or some other track seemingly at random. 

Additionally, I have also experienced the correct title displaying but the wrong audio playing under the same conditions.

**Comment by chr56** [comment]
Well I have confirmed two bugs you described:
- Playing the next track in new queue after you modified the playing queue (such as clicking an item) when `Don't clear my queue` preference **disabled**
- random playing ("the correct title displaying but the wrong audio playing"): currently I found this only **when you modified playing queue** and current track is end then jumps to next, but the "next track" should be played now is actually the "next track" in **old playing queue** instead of new playing queue displayed now, so it random played.

**Comment by chr56** [comment]
> Well I have confirmed two bugs you described:
> 
> * Playing the next track in new queue after you modified the playing queue (such as clicking an item) when `Don't clear my queue` preference **disabled**
> * random playing ("the correct title displaying but the wrong audio playing"): currently I found this only **when you modified playing queue** and current track is end then jumps to next, but the "next track" should be played now is actually the "next track" in **old playing queue** instead of new playing queue displayed now, so it random played.

These bugs should fix soon if thing goes well.

**Comment by chr56** [comment]
They should be fixed now in [0.3.1-beta01](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.3.1-beta01).
@JukeboxZulu 

0.3.1 would be release soon.

**Comment by chr56** [comment]
They should be fixed in release [0.3.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.1).
