### ISSUE TITLE
[Bug] Low quality artwork in notification area.

### ISSUE THREAD

**Issue by perrsona1234** [chr56/Phonograph_Plus#202]
### Bug Summary

Song's artwork in notification area is of low quality. I had similar problem with song's artwork in the app, but I have solved it by disabling "Android MediaStore" in image source configuration (per recommendations I have found in other reported issues). However this didn't solve the problem of low quality of notification area artwork.

### Version

1.7.2.1

### Steps to reproduce the bug

1. Open the app.
2. Play a song with an artwork.
3. Pull down the notification area.
4. Artwork is of low quality.

### Environment

Phone: Moto E7 Power
Android OS version: 10
ROM: Official from Motorola without any modifications

### Screenshots or Screen recordings

Here is a screenshot of the problem compared to two other apps: Auxio (music player) and PipePipe (a fork of NewPipe).
![Screenshot_20240717-121831](https://github.com/user-attachments/assets/aeb011a7-f2a5-4835-bdfd-c0d0523b0286)

**Comment by chr56** [comment]
Since Android R (11), Phonograph Plus provides high quality artwork via `MediaSession` `Metadata` to System (before that version, it uses only `Notification` `LargeIcon` with limited size).
This is because vanilla AOSP use images from `MediaSession` since R (the improved Media Notification as a "new feature" when marketing if I remember).

However, as you can see, the style of Media Notification is not from the vanilla, you device vendor makes some changes of the vanilla.
It seems that:
- Your OS uses `MediaSession` `Metadata` with high quality images. (Phonograph Plus do not provides high quality artwork before Android R)
- Or your OS support larger size for `Notification` `LargeIcon` (Phonograph Plus shrinks images if using `Notification` `LargeIcon`)



Actually, this behavior is distinct from vanilla AOSP. I _am not willing to modify Phonograph Plus for that_. But, I _may_ provide a option in settings for compatibility in future.

**Comment by chr56** [comment]
In Preview version [v1.8.1-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.1-dev1), there is an option to always use Media Session to display images in Section `Compatibility`.

Please check it whether it can help you for your situation.

**Comment by perrsona1234** [comment]
No, it didn't fix my problem.

**Comment by chr56** [comment]
What about this revision: 
[PhonographPlus](https://github.com/user-attachments/files/16402099/PhonographPlus.zip)

**Comment by perrsona1234** [comment]
This one fixed my problem. Thanks.

![Screenshot_20240728-094336](https://github.com/user-attachments/assets/accba6c7-2ee2-43df-a1d7-b982034e8625)

**Comment by chr56** [comment]
[v1.8.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.1) has been released!

Close!
