### ISSUE TITLE
[Bug Report] Lyrics error for opus files although all settings for lyrics are DISABLED

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [chr56/Phonograph_Plus#30]
**Describe the bug or unexpected behavior**
When I play a song, I get a message: "Failed to read lyrics from song
No Reader associated with this extension:opus". I have disabled all settings regarding lyrics. The app should respect those settings and not show an error message.

**Crash log**
Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.3 (311)
Git Commit Hash: fec22849337fddb81837
Android version: 12 (SDK 32)
Device brand:    not important
Device model:    not important
Product name:    lineage_ABC
Build version:   lineage_ABC-userdebug 12
Hardware:        qcom
Language:        it

Failed to read lyrics from song
No Reader associated with this extension:opus

**Comment by chr56** [comment]
Sorry for that, Phonograph Plus currently can not handle `opus` files properly — it can not read its tag (See #9 ).

And Phonograph will automatically try to search lyrics (external or embedded in song tags), however pitifully, there isn't a switch to turn off this "automatically lyrics-fetching".

(So, you can see this error message because Phonograph Plus is trying to search this song's lyrics and since it can't find external lyrics (file `<SONG_FILE_NAME>.lrc`) it try to reading tags for embedded lyrics, so, that's the time error message popup)


I can temperately block the message until solving the `opus` files problem in next version. (And maybe add a switch to turn off lyrics searching & loading as well)

**Comment by chr56** [comment]
BTW, the reading `opus` files tags problem might be done in earlier time of next year or end of this year.

**Comment by klawdhfzasjhaa** [comment]
Thank you. I disabled the error notifications for Phonograph Plus for now.

**Comment by chr56** [comment]
[Phonograph Plus Preview Version](https://github.com/chr56/Phonograph_Plus/files/9623582/previewRelease.zip)

For test

@klawdhfzasjhaa You can enable error notifications now.

**Comment by klawdhfzasjhaa** [comment]
Works! :)

**Comment by chr56** [comment]
close! 
fixed in [v0.3.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.4)
