### ISSUE TITLE
[Feature Request] Index .nomedia & dot(.) folder directories

### ISSUE THREAD

**Issue by AdityaMishra135** [chr56/Phonograph_Plus#38]

**Comment by chr56** [comment]
I am not sure I can achieve that. 

There are two ways listing files now in `Folder` Page (or "View" for some one):
1) Reading from `MediaStore`, and filter them by their path prefix. It is efficient on higher version Androids and requires "less" permission. It's MediaStore's duty to recognize `.nomedia` and `.` prefex file and hide them, and there is nothing I can do or interfere the process because `MediaStore` does not provide ".nomedia" to developers and applications can not read the hidens. This is _default_ mode!
2) (Legacy way) Listing files using system provided api. This require "more" permission and might have trouble in higher version Androids (and slow as well). But developers could access  `.nomedia` and `.` prefex file, so developer can decide the application' behavior by their preferences. You can switch to this mode by checking `Use legacy way to read files` in top-right corner's pop-up.

**Comment by AdityaMishra135** [comment]
I have android version lolipop. So please downgrade it minimum sdk 21 please

**Comment by chr56** [comment]
> I have android version lolipop. So please downgrade it minimum sdk 21 please

Sorry, no longer support Android L, minimum sdk is 24 Android N
