### ISSUE TITLE
[Bug Report] Cannot access SD card from Folders

### ISSUE THREAD

**Issue by xdaft** [chr56/Phonograph_Plus#4]
**Describe the bug or unexpected behavior**

Cannot access SD card from Folders (only built-in is available).

**Crash log**
If app crashed, copy the logs if available.
```
[YOUR LOGS HERE]
```

**How to reproduce**
Steps to reproduce the bugs or unexpected behaviors:

Try to go to folders -> Emulated. It says empty.

**Screenshots (Optional)**
(if available)
Video recording attached.

**Other information**
…
Motorola G 5g Plus. Android 11

https://user-images.githubusercontent.com/2842118/162279262-92a925f7-00d4-4c0d-9d7e-3e4e914b152c.mp4

.

**Comment by chr56** [comment]
Well, that's certainly a bug. However, "Folders" is almost not under a well-maintenance (Actually, I haven't heavily modify and maintain these relative codes since day one of Phonograph Plus). And I am afraid that I might put off maintaining "Folders" (Maybe next month?), because currently I plan to maintain and improve the "bugly", "rusty" and "rickety" background Music Service. If you don't mind, please use "Library" and wait with patience. The "shaky" Folders will be improve and maintain soon.

**Comment by chr56** [comment]
Well, plan changed. Try this [preview build](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0610) (It can installed along with stable release, labeling with `Phonograph Plus Preview`)

**Comment by xdaft** [comment]
Nothing changed with the preview version. There seems to be no regressions.

**Comment by chr56** [comment]
**Using new `Folders`**!
![Screenshot 2022-06-10 232810](https://user-images.githubusercontent.com/30681738/173099516-3c67ece8-839c-49fc-9550-45642b4face3.png)


Click this to switch storage volume.
![Screenshot 2022-06-10 232911](https://user-images.githubusercontent.com/30681738/173099657-d9fac92a-85ab-439e-99ea-a1721eda27eb.png)
![Screenshot 2022-06-10 232829](https://user-images.githubusercontent.com/30681738/173099674-4a9ca9e7-f47b-4da0-9956-d292bbe95e1a.png)

**Comment by xdaft** [comment]
Oh! My bad! I used the folders from the menu instead of the new tab. It works great for me.
