### ISSUE TITLE
[Bug]: Bad search text legibility with a light primary color

### ISSUE THREAD

**Issue by davquar** [chr56/Phonograph_Plus#43]
### Bug Summary

The foreground color of the search bar is white, hence If the user has a light primary color, the legibility is low.

### Version

0.4.0

### Screenshots or Screen recordings

![SmartSelect_20221025-081849_Phonograph Plus](https://user-images.githubusercontent.com/30431538/197801584-9adf9621-50b9-459c-8ccb-9241fd6d35bc.jpg)

**Comment by chr56** [comment]
Confirmed, kind of busy these days, it would be fixed soon (make text contrastes to primary color).

**Comment by chr56** [comment]
![Screenshot_20221026-004740](https://user-images.githubusercontent.com/30681738/197834305-f1a81ea7-219c-4cac-b593-69245216d7da.png)

Since a9d566884864,
work for text is done, the workd for icons are left to be done.

**Comment by chr56** [comment]
![photo_2022-10-28_22-26-24](https://user-images.githubusercontent.com/30681738/198644666-592e9066-b5a1-4186-a4ce-6b6af1e959c0.jpg)

Currently, except 'back' icon and placeholder hint text, the contrast problem was "partially" fixed. -> [v0.4.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.4.1)

Because I am planning to make a brand new Search Page, I have no motive (and no energy) to fix it completely and work on codes that would be removed eventually.

**Comment by chr56** [comment]
By accident, I found where the problem is (the tint-color library "blocks" my manual way to override colors). 

And it finally is fixed since 69e48652 (it should be in next version).


PS: the _overflow menu icon_ ("the three dot" icon) color (which is always white before) is fixed as well.

![Screenshot_20221029-211649](https://user-images.githubusercontent.com/30681738/198833647-2c6578cd-7f29-4b51-824d-e3933eaa2d79.png)

![Screenshot_20221029-211639](https://user-images.githubusercontent.com/30681738/198833645-abb71016-c911-40df-addc-ca3d8afe7f59.png)

**Comment by chr56** [comment]
Closed, due to release of [v0.5.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.0)
