### ISSUE TITLE
[Bug]: Issues with media notification

### ISSUE THREAD

**Issue by Quintus19** [chr56/Phonograph_Plus#80]
### Bug Summary

There are two bugs. First is that the cover art disappears and comes back for a moment when the pause/resume button is toggled.

Second is that the progress bar doesn't reset when I use the "previous" button. The song starts over but the bar remains the same. It continues to progress unless I tap the pause button. Then it returns to it's correct position.

### Version

0.6.2

### Steps to reproduce the bug

Use the previous button through the media notification.

### Environment

OneUI 3.1, Android 11

**Comment by chr56** [comment]
Thank you!

1) Actually, I do not want to call it a "bug", it can be a "feature" somehow (or "trait" technically).The toggling of pause/resume button can refresh Media Notification (leading to reloading of the artwork)

2) this fixed in [v0.6.2.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.6.2.1).

**Comment by Quintus19** [comment]
Thank you for the fix! I appreciate the work you do here.
Also here's something while I'm at it: I would really appreciate it if the cover art renders through the status bar on "Card" mode. (Well it is being rendered but it's blocked by the status bar)
