### ISSUE TITLE
[Bug]: A minor issue of word spelling

### ISSUE THREAD

**Issue by Gluneklairo** [chr56/Phonograph_Plus#85]
### Bug Summary

While the language is set to English (US), some words are in British English form.
While the language is set to English (UK), some words are in American English form.
And some words didn't change form after swapping language.
For example, "Equalizer", "behavior", "favorite", "dialog"

### Version

0.6.3

### Steps to reproduce the bug

Swap language and see.

**Comment by chr56** [comment]
Actually, that is a bug of switching Language. These "English"es can not switch among themselves correctly.

Now, the problem _should_ be fixed in [v0.7.0-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.0-dev2).

But this version also supports Android T's "Per-app Language Preference", there might be some similar problems if you switch in App Info of system.

**Comment by chr56** [comment]
Stable [v0.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.0) should not have such problems now.
