### ISSUE TITLE
[Bug Report] Tag Editor can't edit OPUS files

### ISSUE THREAD

**Issue by anaskaejdar** [chr56/Phonograph_Plus#9]
**Describe the bug or unexpected behavior**
If you edit the tags of an opus file, Phonograph+ will give you a notification with error message that says, «Failed to save tags» «a» «No Reader associated with this extension:opus»

An opus file uses the same tag format as OGG vorbis as far as I know, so it should work as long as Phonograph+ knows to treat the tags like OGG vorbis tags

**Crash log**
If app crashed, copy the logs if available.
```
n/a
```

**How to reproduce**
Steps to reproduce the bugs or unexpected behaviors:
Edit an OPUS file's tags. Save the changes. Observe this message:

**Screenshots (Optional)**
![Screenshot_۲۰۲۲۰۵۲۸-۱۱۵۱۳۰_Fennec](https://user-images.githubusercontent.com/32847759/170839085-b3f57ec8-6989-4f90-bab6-6bfcf297aa44.jpg)

**Other information**
…

**Comment by chr56** [comment]
Well, Phonograph Plus currently can not support reading/writing tags of opus format though it seems that opus has the same tag structure with ogg format.
Sorry for that!

**Comment by maemunman** [comment]
No worries. If it helps, Opus files actually are genuine OGG files using the actual OGG container format. The only difference from OGG-Vorbis is that OGG-OPUS files use the OPUS codec rather than Vorbis, but still all within the OGG container. It is even perfectly legitimate for Opus files to have a .ogg extension and everything. If the tag editor knows to treat .opus as equivalent of .ogg, all should be well.

**Comment by chr56** [comment]
Opus format should be supported since [v0.5.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.4).

Ready for closing.
