### ISSUE TITLE
[Bug]: lyrics issue

### ISSUE THREAD

**Issue by LissomPaladin** [chr56/Phonograph_Plus#98]
### Bug Summary

When I load lyrics using the "choose lyrics" option it loads for just one time and when i play that song again the lyrics just disappear 

### Version

0.7.2

### Environment

I'm running miui 14 . 
Global ROM

**Comment by chr56** [comment]
I am sorry. This is not a bug, _~is a feature~_😅.

Menu item `Choose Lyrics` is **"One-shot" only**. This means, the loaded lyrics can only be showed for the moment playing the song; once the song ends, the loaded lyrics won't show again.


____________

In order to make it persistent, please do one of these following operations:

Method A: _rename and move the lyrics_ (suggested)

1. Move your lyrics to its song, make sure lyrics and its song are in same folder.
2. Rename file name of lyrics to song file's name. (It doesn't matter if you add a suffix or a prefix to its name matching the corresponded song file)

Method B: _embed the lyrics to song_

Use other tag editors to embed the lyrics text to the music tag in the song file.


____________

Lyrics would be automatically loaded after these operations.

<br/>
Note^1: Currently Phonograph Plus supports only `lrc` (synchronized) format and `txt` (un-synchronized, only plain text can be viewed)
Note^2: Make sure you enable the lyrics in `Setting`
